spring:
  application:
    name: CarRenting
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    url: jdbc:postgresql://dpg-ctfi9h56l47c73b924i0-a.oregon-postgres.render.com:5432/carrentingdb
    username: carrentingdb_user
    password: W0DcYby8c95CSksY8VZsdLz7zqog69K1
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/
