spring:
  application:
    name: CarRenting
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
  datasource:
    url: dpg-crcrlv2j1k6c73csad6g-a
    username: kent
    password: wf3M3dWYtWgpGl16jjO633on8MfEKl5g
    driver-class-name: org.postgresql.Driver
    port: 5432
  jpa:
    hibernate:
      ddl-auto: create-drop
springdoc:
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/

