spring:
  datasource:
    url: jdbc:postgresql://dpg-crcrlv2j1k6c73csad6g-a.oregon-postgres.render.com:5432/car_renting_garc
    username: kent
    password: wf3M3dWYtWgpGl16jjO633on8MfEKl5g
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.JBossAppServerJtaPlatform

  mail:
    host: smtp.gmail.com
    port: 587
    username: intelligencea61@gmail.com
    password: lvte cvaw lfdp mfhz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:3000/activate-account

server:
  port: 8080